### ISSUE TITLE
Minimum Viable Product

### ISSUE THREAD

**Issue by devinleonhart** [aaronpflaumer/sleek-edit#1]
Alright, @aaronpflaumer . We're going to use this repository for your training as a developer. We're going to pretend I'm an employer who knows enough about Github and the project to direct you while also providing due dates for the tasks.

The first task is one that can easily be achieved in a few hours. Minimum Viable Product. You have two locations you can store information about your project, please choose one, the other, or both.
1. Make a `/documents` folder in your repository and add to it an `.md` file that explains the Minimum viable product for Sleek Edit. 
2. Use the Github wiki for the same.

`Minimum Viable Product` is the absolute minimum it will take for the customer (me) to be happy. Normally this is done as an interview between you and the client to figure out what that is. But since this is your project, that would be unrealistic. Create a document that explains the minimum viable product. This includes platforms it's expected to run on as well as the functionality it is expected to perform. It can be as simple as a paragraph but detail really helps in getting you out of trouble-spots later.

**Comment by devinleonhart** [comment]
We're also using the concept of Milestones on this project. A Milestone is an agreed-upon time that collections of tasks will be finished. This is also your motivation to work harder or slower. If a milestone is passed and there's no good reason for it, the client/employer has a reason to get angry. We're going to use these to simulate a professional relationship. The documentation Milestone has a Wednesday due date, which is always assumed to be "end of day" on the due date.

**Comment by aaronpflaumer** [comment]
4d6af5ef13e54931e009baac256d222dec0fe813
