### ISSUE TITLE
UI Wireframes

### ISSUE THREAD

**Issue by devinleonhart** [aaronpflaumer/sleek-edit#2]
After you're finished with #1 , you should have a good idea of what the product is expected to do at the bare minimum. Construct wireframes of non-trivial areas of the application. A typical wireframe would be for the "home screen" of the app where a majority of controls are provided to the user.

The wireframe step is to prevent "painting yourself into a corner" by making sure you think of all the buttons and functionality an app needs and where you'd put them before you start. This prevents clunky, crappy UIs.

Make at least one Wireframe for sleek-edit, preferably areas where users will spend 90% of their time. Avoid things like settings menus or forms. As those are just trivial lists and don't require framing.Submit them to the same document locations you chose in #1

**Comment by aaronpflaumer** [comment]
6ab5e08ec56d39743fa16e5af825a841803ee4aa
