### ISSUE TITLE
Scaffolding, LICENSE, & README

### ISSUE THREAD

**Issue by devinleonhart** [aaronpflaumer/sleek-edit#3]
Normally, you'd have more time for scaffolding. But I'm including it here because it's already done with the work we did together. The last part of documentation, for now, is to make sure the README file is as robust as it can be. Make sure it has these two things -
1. Command examples and steps a brand-new developer would have to take to get your project running in a development environment. (This is normally not required if you don't intend on sharing your project with others.) Any other documentation for environment like Production and Testing will be saved for later.
2. A good description of what the project is what need the project is intending to fill.

Last, make sure you have chosen a LICENSE that reflects your long term goals.

MIT - This is generally selected as the "I don't care. You can use it." option.
`The MIT License is a free software license originating at the Massachusetts Institute of Technology (MIT). It is a permissive free software license, meaning that it permits reuse within proprietary software provided all copies of the licensed software include a copy of the MIT License terms and the copyright notice.`

GPLv3 - This is used for confidently stating your project is open source and must remain that way. Anything you're work is included into must also be Open Source.

```
The licenses for most software and other practical works are designed to take away your freedom to share and change the works. By contrast, the GNU General Public License is intended to guarantee your freedom to share and change all versions of a program--to make sure it remains free software for all its users. We, the Free Software Foundation, use the GNU General Public License for most of our software; it applies also to any other work released this way by its authors. You can apply it to your programs, too.
```

And, of course, if you intend to keep it closed source, you will have to make this a private repo so others cannot see it and then take out copyright on the software. Being open source doesn't mean "free", though. You can still sell access or instances of the code. We're mostly talking about people being able to use your work in their work.

**Comment by aaronpflaumer** [comment]
Readme:
eadc5e73e2a907fc488413eb86d0193d1f3090dd

License:
b4ff21333ad5a51927fc9a150351c4d2c9a1fbac
