### ISSUE TITLE
Routing, Views and Controllers

### ISSUE THREAD

**Issue by devinleonhart** [aaronpflaumer/sleek-edit#4]
Now that you've got an idea for all the views your app needs to have and wireframes for them, it's time to scaffold out the routing for your application.

_Routing_ means "loading markup and javascript when the user visits a particular URL" Since we use the term Routing to describe this, we call the URLs "Routes."

You will be using https://github.com/angular-ui/ui-router to achieve this. UI-Router is preferred over ng-route because ui-router treats your app like a state machine. This makes it very easy to track the state of your app and what templates should be loaded at what time. For example, if I saw a state called `cart.order-confirm` for a shopping site I know I am on the shopping cart view, with the `order-confirm` templates and logic loaded into that view.

Set up routing for your application using ui-router and make the "root-route" the primary application view where the user will be doing the most work. The "root-route" is the route that the application will use when a visitor visits `/` of your app. Do not make this the login page, as we will make your app detect when someone is not logged in and reroute them to a `/login` route.

Also, you will need to make sure there is a controller available for every route that performs unique functionality. For now, create a controller for every new route and we will optimize as we go along.

**Comment by devinleonhart** [comment]
@aaronpflaumer Any updates?

**Comment by aaronpflaumer** [comment]
@devinleonhart Nothing yesterday. Working on things now.

**Comment by aaronpflaumer** [comment]
Although I do have the routes created...I didn't feel like they were polished enough to close this issue but I suppose having them is enough.

**Comment by devinleonhart** [comment]
@aaronpflaumer Closing in on the prototype due date. Any updates on progress? Things have been silent.
